// Super Admin Dashboard - Overview and management interface
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import './Dashboard.css';

export default function AdminDashboard() {
  const [stats, setStats] = useState(null);
  const [recentDocuments, setRecentDocuments] = useState([]);
  const [loading, setLoading] = useState(true);
  const { token, logout, user } = useAuth();
  const navigate = useNavigate();

  const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000';

  useEffect(() => {
    fetchDashboardData();
  }, []);

  const fetchDashboardData = async () => {
    try {
      const response = await fetch(`${API_URL}/api/admin/dashboard`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (response.ok) {
        const data = await response.json();
        setStats(data.stats);
        setRecentDocuments(data.recentDocuments || []);
      }
    } catch (error) {
      console.error('Failed to fetch dashboard:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  if (loading) {
    return <div className="dashboard-loading">Loading...</div>;
  }

  return (
    <div className="dashboard">
      <nav className="dashboard-nav">
        <div className="nav-brand">
          <h2>Mujaa Admin</h2>
        </div>
        <div className="nav-user">
          <span>Welcome, {user?.full_name}</span>
          <button onClick={handleLogout} className="btn-logout">Logout</button>
        </div>
      </nav>

      <div className="dashboard-content">
        <h1>Dashboard</h1>

        <div className="stats-grid">
          <div className="stat-card">
            <h3>Active Staff</h3>
            <p className="stat-number">{stats?.active_staff || 0}</p>
          </div>
          <div className="stat-card">
            <h3>Total Documents</h3>
            <p className="stat-number">{stats?.total_documents || 0}</p>
          </div>
          <div className="stat-card">
            <h3>Pending</h3>
            <p className="stat-number">{stats?.pending_documents || 0}</p>
          </div>
          <div className="stat-card">
            <h3>Submitted Today</h3>
            <p className="stat-number">{stats?.documents_today || 0}</p>
          </div>
        </div>

        <div className="dashboard-sections">
          <div className="section">
            <h2>Quick Actions</h2>
            <div className="action-buttons">
              <button className="btn-action" onClick={() => navigate('/admin/users')}>
                Manage Users
              </button>
              <button className="btn-action" onClick={() => navigate('/admin/documents')}>
                View All Documents
              </button>
              <button className="btn-action" onClick={() => navigate('/admin/activity')}>
                Activity Logs
              </button>
              <button className="btn-action" onClick={() => navigate('/admin/settings')}>
                System Settings
              </button>
            </div>
          </div>

          <div className="section">
            <h2>Recent Documents</h2>
            <div className="table-container">
              <table>
                <thead>
                  <tr>
                    <th>Policy #</th>
                    <th>Client Name</th>
                    <th>Status</th>
                    <th>Generated By</th>
                    <th>Date</th>
                  </tr>
                </thead>
                <tbody>
                  {recentDocuments.length === 0 ? (
                    <tr>
                      <td colSpan="5" style={{textAlign: 'center'}}>No documents yet</td>
                    </tr>
                  ) : (
                    recentDocuments.map((doc) => (
                      <tr key={doc.id}>
                        <td>{doc.policy_number}</td>
                        <td>{doc.client_name}</td>
                        <td>
                          <span className={`status-badge status-${doc.status}`}>
                            {doc.status}
                          </span>
                        </td>
                        <td>{doc.generated_by_name}</td>
                        <td>{new Date(doc.generated_at).toLocaleDateString()}</td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

